# Generated by Django 5.2.3 on 2026-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_study_time",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning"),
                    ("EVENING", "Evening"),
                    ("NIGHT", "Night"),
                ],
                default="MORNING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weekly_goal_hours",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
