# Generated by Django 5.2.3 on 2026-10-01 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_preferred_study_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_study_minutes_weekday',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)], verbose_name='Tempo Diário Dias Úteis (minutos)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_study_minutes_weekend',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Tempo Diário Fim de Semana (minutos)'),
        ),
    ]
