# Generated by Django 5.2.3 on 2026-04-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_userprofile_dailyreminderlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
