# Generated by Django 5.2.3 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_studyinsight"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="completion_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="completion_summary",
            field=models.TextField(blank=True),
        ),
    ]
