# Generated by Django 5.2.3 on 2026-10-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_complete_study_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Extremamente Importante'), ('MEDIUM', 'Média Importância'), ('LOW', 'Baixa Importância')], db_index=True, default='MEDIUM', max_length=10),
        ),
    ]
