# Generated by Django 5.2.3 on 2026-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_topic_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'Extremamente Importante'), ('MEDIUM', 'Média Importância'), ('LOW', 'Baixa Importância')], db_index=True, default='MEDIUM', max_length=10),
        ),
    ]
