# Generated by Django 5.2.3 on 2026-10-01 19:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_topic_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)])),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='task.weeklyplan')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plan_items', to='task.topic')),
            ],
            options={
                'ordering': ['day_of_week', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['user', 'week_start'], name='task_weekly_user_id_02e25c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together={('user', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='weeklyplanitem',
            index=models.Index(fields=['plan', 'day_of_week', 'order'], name='task_weekly_plan_id_8ae9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplanitem',
            index=models.Index(fields=['plan', 'is_completed'], name='task_weekly_plan_id_166e4c_idx'),
        ),
    ]
